@startuml Hospedagem

entity pessoa{
    id <<PK>>
    telefone
    pais
    estado
    endereco
    cidade
    cep
}


CREATE SEQUENCE pessoa_id_seq
INCREMENT 1
START 1
CACHE 1;

ALTER TABLE pessoa ALTER COLUMN id SET DEFAULT NEXTVAL('pessoa_id_seq');

entity pessoa_fisica{
    id <<PK>>
    nome
    cpf
    rg
    genero
    data_nascimento
    telefone_emergencia
    id_pessoa <<FK>>
}


CREATE SEQUENCE pessoa_fisica_id_seq
INCREMENT 1
START 1
CACHE 1;

ALTER TABLE pessoa_fisica ALTER COLUMN id SET DEFAULT NEXTVAL('pessoa_fisica_id_seq');




entity pessoa_juridica{
    id <<PK>>
    cnpj
    razao_social
    nome_fantasia
    data_abertura
    id_pessoa <<FK>>
}

CREATE SEQUENCE pessoa_fisica_id_seq
INCREMENT 1
START 1
CACHE 1;

ALTER TABLE pessoa_juridica ALTER COLUMN id SET DEFAULT NEXTVAL('pessoa_juridica_id_seq');


entity cargo{
    id <<PK>>
}

CREATE SEQUENCE cargo_id_seq
INCREMENT 1
START 1
CACHE 1;

ALTER TABLE cargo ALTER COLUMN id SET DEFAULT NEXTVAL('cargo_id_seq');


entity funcionario{
    id <<PK>>
    matricula
    data_admissao
    situacao
    id_cargo <<FK>>
    id_pessoa_fisica <<FK>>
}

CREATE SEQUENCE funcionario_id_seq
INCREMENT 1
START 1
CACHE 1;

ALTER TABLE funcionario ALTER COLUMN id SET DEFAULT NEXTVAL('funcionario_id_seq');


entity reserva{
    id <<PK>>
    id_pessoa <<FK>>
}

CREATE SEQUENCE reserva_id_seq
INCREMENT 1
START 1
CACHE 1;

ALTER TABLE reserva ALTER COLUMN id SET DEFAULT NEXTVAL('reserva_id_seq');


entity hospedagem{
    id_reserva <<FK>>
    id_pessoa_fisica <<FK>>
}

entity tipo_local_hospedagem{
    id <<PK>>
}

CREATE SEQUENCE tipo_local_hospedagem_id_seq
INCREMENT 1
START 1
CACHE 1;

ALTER TABLE tipo_local_hospedagem ALTER COLUMN id SET DEFAULT NEXTVAL('tipo_local_hospedagem_id_seq');


entity local_hospedagem{
    id <<PK>>
    id_hospedagem <<FK>>
    id_tipo_local_hospedagem <<FK>>
}

CREATE SEQUENCE local_hospedagem_id_seq
INCREMENT 1
START 1
CACHE 1;

ALTER TABLE local_hospedagem ALTER COLUMN id SET DEFAULT NEXTVAL('local_hospedagem_id_seq');


entity tipo_quarto{
    id <<PK>>
}


CREATE SEQUENCE tipo_quarto_id_seq
INCREMENT 1
START 1
CACHE 1;

ALTER TABLE tipo_quarto ALTER COLUMN id SET DEFAULT NEXTVAL('tipo_quarto_id_seq');

entity quarto{
    id <<PK>>

    id_tipo_quarto <<FK>>
    id_hospedagem <<FK>>
}

CREATE SEQUENCE quarto_id_seq
INCREMENT 1
START 1
CACHE 1;

ALTER TABLE quarto ALTER COLUMN id SET DEFAULT NEXTVAL('quarto_id_seq');



entity servico{
    id <<PK>>
}

CREATE SEQUENCE servico_id_seq
INCREMENT 1
START 1
CACHE 1;

ALTER TABLE servico ALTER COLUMN id SET DEFAULT NEXTVAL('servico_id_seq');

entity servico_funcionario_hospedagem{
    id_servico <<FK>>
    id_funcionario <<FK>>
    id_hospedagem <<FK>>
}

entity produto{
    id <<PK>>
    id_local_hospedagem <<FK>>
}


CREATE SEQUENCE produto_id_seq
INCREMENT 1
START 1
CACHE 1;

ALTER TABLE produto ALTER COLUMN id SET DEFAULT NEXTVAL('produto_id_seq');

entity comanda_produto{
    id_comanda <<FK>>
    id_produto <<FK>>
}

entity comanda{
    id <<PK>>
    id_produto <<FK>>
    id_pessoa <<FK>>
}


CREATE SEQUENCE comanda_id_seq
INCREMENT 1
START 1
CACHE 1;

ALTER TABLE comanda ALTER COLUMN id SET DEFAULT NEXTVAL('comanda_id_seq');

pessoa -- pessoa_fisica
pessoa -- pessoa_juridica

pessoa_fisica -- funcionario

funcionario -- cargo

reserva -- pessoa

hospedagem -- reserva
hospedagem -- pessoa_fisica

local_hospedagem -- tipo_local_hospedagem

quarto -- tipo_quarto
quarto -- local_hospedagem
quarto -- hospedagem

servico_funcionario_hospedagem -- servico
servico_funcionario_hospedagem -- funcionario
servico_funcionario_hospedagem -- hospedagem

produto -- local_hospedagem

comanda -- hospedagem

comanda_produto -- comanda
comanda_produto -- produto

@enduml